state:

  # Upper and lower bounds for experimental space (meters). [x, y, z]
  lower: [-2.0, -1.04, 0] 
  upper: [1.66, 2.62, 2.0] 

pred:

  # Dimensions of the prediction map
  sim_height: 26
  sim_width: 26

  # Start position of human and list of potential goal locations
  # 
  # Exp. 1) side-by-side robot and human:
  #   real_start [1.4,-0.2]
  #   real_goals: [[1.4,2.0]]

  real_start: [1.61,-1.02]
  real_goals: [[-0.52, 2.60]] #[-2.0, 0.78]]

  #real_start: [-1.049, 0.783] #[-1.988, -1.023]
  #real_goals: [[1.650, 0.480]] #[-0.465, 2.636]]

  # robot_start: [-1.069,-0.713, 2.0]
  # robot_goal: [1.33, 2.26]

  # Resolution, ex. (real meters)/(sim dim-1) (m/cell)
  resolution: 0.1464 

  # Num timesteps into the future to predict
  fwd_tsteps: 10

  # Initial betas 
  betas: [0.1, 0.3, 1.0, 3.0, 10.0]
  #betas: [0.05]

  # Human's height (in meters)
  human_height: 1.67

  # Human's walking speed (m/s) -- human walking speed is 1.4 m/s
  human_vel: 1.4

  # Probability threshold 
  prob_thresh: 0.25
