state:

  # Upper and lower bounds for state space.
  # In the quadrotor 6D model, state is [x, y, z, vx, vy, vz].
  upper: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
  lower: [-10.0, -10.0, 0.0, -10.0, -10.0, -10.0]

pred:

  # Dimensions of the prediction map
  sim_height: 20
  sim_width: 20

  # Start position of human and list of potential goal locations
  sim_start: [0, 0]
  sim_goals: [[19, 10]]

  # Resolution, ex. 20 meters/10 sim dim (m/cell)
  resolution: 1

  # Num timesteps into the future to predict
  fwd_tsteps: 10

  # Time between each step (in seconds?)
  fwd_deltat: 1

  # Initial rationality coefficient 
  init_beta: 0.5

  # Human's height (in m?)
  human_height: 5

  # Probability threshold 
  prob_thresh: 0.1
