state:

  # Upper and lower bounds for experimental space (meters). [x, y, z]
  lower: [-2.0, -1.04, 0] 
  upper: [1.66, 2.62, 2.0] 

pred:

  # Dimensions of the prediction map
  sim_height: 26
  sim_width: 26

  # Start position of human and list of potential goal locations
  sim_start: [0, 0]
  sim_goals: [[13,25], [25,13]] 

  real_start: [1.0,-0.2] #[1.650, -1] 
  real_goals: [[1.0, 2.0]]

  # Resolution, ex. (real meters)/(sim dim-1) (m/cell)
  resolution: 0.1464 

  # Num timesteps into the future to predict
  fwd_tsteps: 10

  # Time between each step (in seconds?)
  fwd_deltat: 1

  # Initial rationality coefficient 
  init_beta: 0.5

  # Human's height (in meters)
  human_height: 1.67

  # Probability threshold 
  prob_thresh: 0.1
