state:

  # Upper and lower bounds for state space.
  # In the quadrotor 6D model, state is [x, y, z, vx, vy, vz].
  lower: [-20.0, -20.0, 0.0, -1.0, -1.0, -1.0]
  upper: [20.0, 20.0, 20.0, 1.0, 1.0, 1.0]

pred:

  # Dimensions of the prediction map
  sim_height: 40
  sim_width: 40

  # Start position of human and list of potential goal locations
  sim_start: [0, 0]
  sim_goals: [[39, 39]] #[20, 39], [39, 20]

  # Resolution, ex. 20 meters/10 sim dim (m/cell)
  resolution: 1

  # Num timesteps into the future to predict
  fwd_tsteps: 10

  # Time between each step (in seconds?)
  fwd_deltat: 1

  # Initial rationality coefficient 
  init_beta: 0.5

  # Human's height (in m?)
  human_height: 5

  # Probability threshold 
  prob_thresh: 0.1
